# Generated by Django 2.1.7 on 2019-12-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191203_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
