# Generated by Django 2.1.7 on 2019-12-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wall_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='core.Recommendation'),
        ),
    ]
