# Generated by Django 2.1.7 on 2019-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191209_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='food',
        ),
        migrations.AddField(
            model_name='wall',
            name='food',
            field=models.ManyToManyField(related_name='block', to='core.Food'),
        ),
    ]
