# Generated by Django 2.1.7 on 2019-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191209_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='compatibility',
            field=models.ManyToManyField(blank=True, null=True, to='core.Compatibility'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='water',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
