# Generated by Django 2.1.7 on 2019-12-03 15:54

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.document_path, validators=[utils.validators.document_extension]),
        ),
    ]
